obstacle_range: 2.5
raytrace_range: 4.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.30
inflation_radius: 0.35

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: camera_depth_link, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}
